library(GSEABase)
library(tidyverse)

#########################################################################
# Script to map DEG enriched GO terms to GOslims
# and identify the GO terms contributing to each GOslim

# Expects a "flattened" GOseq erniched file generated by Trinity
# DEG determination from edgeR.
#########################################################################

### Download required GOslim file
download.file(url = "http://current.geneontology.org/ontology/subsets/goslim_generic.obo", 
              destfile = "./data/goslim_generic.obo")

### Download files and specify destination directory
download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/44_k4/edgeR.28505.dir/salmon.gene.counts.matrix.44_vs_k4.edgeR.DE_results.P0.05_C1.44-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/44_k4/salmon.gene.counts.matrix.44_vs_k4.edgeR.DE_results.P0.05_C1.44-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/44_k4/edgeR.28505.dir/salmon.gene.counts.matrix.44_vs_k4.edgeR.DE_results.P0.05_C1.k4-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/44_k4/salmon.gene.counts.matrix.44_vs_k4.edgeR.DE_results.P0.05_C1.k4-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached-44_bleached-k4/edgeR.26712.dir/salmon.gene.counts.matrix.bleached-44_vs_bleached-k4.edgeR.DE_results.P0.05_C1.bleached-44-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached-44_bleached-k4/salmon.gene.counts.matrix.bleached-44_vs_bleached-k4.edgeR.DE_results.P0.05_C1.bleached-44-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached-44_bleached-k4/edgeR.26712.dir/salmon.gene.counts.matrix.bleached-44_vs_bleached-k4.edgeR.DE_results.P0.05_C1.bleached-k4-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached-44_bleached-k4/salmon.gene.counts.matrix.bleached-44_vs_bleached-k4.edgeR.DE_results.P0.05_C1.bleached-k4-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached-44_non-bleached-44/edgeR.16980.dir/salmon.gene.counts.matrix.bleached-44_vs_non-bleached-44.edgeR.DE_results.P0.05_C1.bleached-44-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached-44_non-bleached-44/salmon.gene.counts.matrix.bleached-44_vs_non-bleached-44.edgeR.DE_results.P0.05_C1.bleached-44-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached-44_non-bleached-44/edgeR.16980.dir/salmon.gene.counts.matrix.bleached-44_vs_non-bleached-44.edgeR.DE_results.P0.05_C1.non-bleached-44-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached-44_non-bleached-44/salmon.gene.counts.matrix.bleached-44_vs_non-bleached-44.edgeR.DE_results.P0.05_C1.non-bleached-44-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached-k4_non-bleached-k4/edgeR.7074.dir/salmon.gene.counts.matrix.bleached-k4_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.bleached-k4-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached-k4_non-bleached-k4/salmon.gene.counts.matrix.bleached-k4_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.bleached-k4-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached-k4_non-bleached-k4/edgeR.7074.dir/salmon.gene.counts.matrix.bleached-k4_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.non-bleached-k4-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached-k4_non-bleached-k4/salmon.gene.counts.matrix.bleached-k4_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.non-bleached-k4-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached_non-bleached/edgeR.9633.dir/salmon.gene.counts.matrix.bleached_vs_non-bleached.edgeR.DE_results.P0.05_C1.bleached-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached_non-bleached/salmon.gene.counts.matrix.bleached_vs_non-bleached.edgeR.DE_results.P0.05_C1.bleached-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/bleached_non-bleached/edgeR.9633.dir/salmon.gene.counts.matrix.bleached_vs_non-bleached.edgeR.DE_results.P0.05_C1.non-bleached-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/bleached_non-bleached/salmon.gene.counts.matrix.bleached_vs_non-bleached.edgeR.DE_results.P0.05_C1.non-bleached-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/non-bleached-44_non-bleached-k4/edgeR.4792.dir/salmon.gene.counts.matrix.non-bleached-44_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.non-bleached-44-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/non-bleached-44_non-bleached-k4/salmon.gene.counts.matrix.non-bleached-44_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.non-bleached-44-UP.subset.GOseq.enriched.flattened")

download.file(url = "https://raw.githubusercontent.com/kubu4/coral_rnaseq_2017/daae8464b884786cb96ee547785067d453d060e2/analyses/montipora/20211015_mcap_DEG_pairwise_comparisons/non-bleached-44_non-bleached-k4/edgeR.4792.dir/salmon.gene.counts.matrix.non-bleached-44_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.non-bleached-k4-UP.subset.GOseq.enriched.flattened", 
              destfile = "./data/non-bleached-44_non-bleached-k4/salmon.gene.counts.matrix.non-bleached-44_vs_non-bleached-k4.edgeR.DE_results.P0.05_C1.non-bleached-k4-UP.subset.GOseq.enriched.flattened")



### Set false discovery rate (FDR) filter, if desired
fdr <- as.character("1.0")

### Create list of files
goseq_files <- list.files(path = "./data",
                          pattern = "\\.GOseq.[de]",
                          recursive = TRUE,
                          full.names = TRUE)

### Set GOslim output filename suffix
goslim_output_suffix=("GOslims.csv")

### Set REVIGO output filename suffix
revigo_output_suffix=("revigo.tab")

### Strip path from goseq files
goseq_filename <- basename(goseq_files)

### Vector of GOslim ontologies (e.g. Biological Process = BP, Molecular Function = MF, Cellular Component = CC)
ontologies <- c("BP", "CC", "MF")

for (slim_ontology in ontologies) {
  
  ### Set GOOFFSPRING database, based on ontology group set above
  go_offspring <- paste("GO", slim_ontology, "OFFSPRING", sep = "")
  
  for (item in goseq_files) {
    
    
    ## Get max number of fields
    # Needed to handle reading in file with different number of columns in each row
    # as there may be multiple
    max_fields <- max(count.fields(item, sep = "\t"), na.rm = TRUE)
    
    ## Read in tab-delimited GOseq file
    # Use "max_fields" to populate all columns with a sequentially numbered header
    go_seqs <- read.delim(item,
                          col.names = paste0("V",seq_len(max_fields)))
    
    ## Filter enriched GOterms with false discovery rate
    goseqs_fdr <- filter(go_seqs, V8 <= as.numeric(fdr))
    
    ## Grab just the individual GO terms from the "category" column)
    goterms <- as.character(goseqs_fdr$V1)
    
    ### Use GSEA to map GO terms to GOslims
    
    ## Store goterms as GSEA object
    myCollection <- GOCollection(goterms)
    
    ## Use generic GOslim file to create a GOslim collection
    
    # I downloaded goslim_generic.obo from http://geneontology.org/docs/go-subset-guide/
    # then i moved it to the R library for GSEABase in the extdata folder
    # in addition to using the command here - I think they're both required.
    slim <- getOBOCollection("./data/goslim_generic.obo")
    
    ## Map GO terms to GOslims and select Biological Processes group
    slimsdf <- goSlim(myCollection, slim, slim_ontology)
    
    ## Need to know the 'offspring' of each term in the ontology, and this is given by the data in:
    # GO.db::getFromNamespace(go_offspring, "GO.db")
    
    ## Create function to parse out GO terms assigned to each GOslim
    ## Courtesy Bioconductor Support: https://support.bioconductor.org/p/128407/
    mappedIds <-
      function(df, collection, OFFSPRING)
      {
        map <- as.list(OFFSPRING[rownames(df)])
        mapped <- lapply(map, intersect, ids(collection))
        df[["go_terms"]] <- vapply(unname(mapped), paste, collapse = ";", character(1L))
        df
      }
    
    ## Run the function
    slimsdf <- mappedIds(slimsdf, myCollection, getFromNamespace(go_offspring, "GO.db"))
    
    ## Provide column name for first column
    slimsdf <- cbind(GOslim = rownames(slimsdf), slimsdf)
    rownames(slimsdf) <- NULL
    
    ## Pull out GO terms matching set GOslim ontology
    revigo_bp_df <- subset(go_seqs, V7 == slim_ontology, select = c(V1, V2))
    
    ### Prep output file naming structure
    
    ## Split filenames on periods
    ## Creates a list
    split_filename <- strsplit(item, ".", fixed = TRUE)
    
    ## Split filename on directories
    ## Creates a list
    split_dirs <- strsplit(item, "/", fixed = TRUE)
    
    ## Slice split_filename list from position 9 to the last position of the list
    ## Paste these together using a period
    goseq_filename_split <-paste(split_filename[[1]][9:lengths(split_filename)], collapse = ".")
    
    ## Slice split_dirs list at position
    
    ## Paste elements together to form GOslim output filename
    fdr_file_out <- paste("FDR", fdr, sep = "_")
    goslim_outfilename <- paste(goseq_filename_split, fdr_file_out, slim_ontology, goslim_output_suffix, collapse = ".", sep = ".")
    
    ## Paste elements together to form REVIGO output filename
    revigo_outfilename <- paste(goseq_filename_split, fdr_file_out, slim_ontology, revigo_output_suffix, collapse = ".", sep = ".")
    
    ## Set output file destination and name
    ## Adds proper subdirectory from split_dirs list
    goslim_outfile_dest <- file.path("./analyses", split_dirs[[1]][3], goslim_outfilename)
    revigo_outfile_dest <- file.path("./analyses", split_dirs[[1]][3], revigo_outfilename)
    
  
    ## Write revigo output file
    write.table(revigo_bp_df, file = revigo_outfile_dest, quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t")
    
    ## Write output file
    write.csv(slimsdf, file = goslim_outfile_dest, quote = FALSE, row.names = FALSE)
    
    
  }
}
