# Script to generate a "pyramid" plot
# comparing the percentages of enriched GO terms assigned
# to each category of Biological Process GOslims.

# Expects a CSV file generated by the "go_goslims.R" script, having the following filename format (with these column headers):

# comparison, "/P0.05_C1.", treatment_01, "-UP.subset.GOseq.enriched.flattened.FDR_1.0.BP.GOslims.csv"

# and the following column names

## GOslim,Count,Percent,Term,go_terms

## The "go_terms" column is a semi-colon delimited set of GO terms.

# A corresponding directory for each expected comparison must exist in the ./data AND ./figures directories prior to running!
## Comparisons need to be separated by an underscore for downstream parsing.
## E.g. infected_uninfected
## E.g. D01-infected_D12-uninfected


# Outputs a "pyramid" plot of percentages of GO terms assigned to each GOslim in each treatment.


library(dplyr)
library(ggplot2)



################# No other underscores may be used in the directory names #######################
comparisons <- list.dirs(path = "./data/", full.names = FALSE, recursive = FALSE)


######################################################
# CHANGES BELOW HERE ARE PROBABLY NOT NECESSARY
######################################################

for (comparison in comparisons) {
  # Treatments
  ## Split comparison into list of two elements
  treatments_list <- strsplit(comparison, "_")
  
  ## Assign treatments
  treatment_01 <- treatments_list[[1]][1]
  treatment_02 <- treatments_list[[1]][2]
  
  # Read in first comparison files
  df1 <- read.csv(paste("analyses/", comparison, "/P0.05_C1.", treatment_01, "-UP.subset.GOseq.enriched.flattened.FDR_1.0.BP.GOslims.csv", sep = ""))
  
  # Read in second comparison file
  df2 <- read.csv(paste("analyses/", comparison, "/P0.05_C1.", treatment_02, "-UP.subset.GOseq.enriched.flattened.FDR_1.0.BP.GOslims.csv", sep = ""))
  
  # GOslim categories
  ontologies <- c("BP", "CC", "MF")
  
  # Remove generic "biological_process" category
  df1 <- df1[df1$GOslim != "GO:0008150",]
  df2 <- df2[df2$GOslim != "GO:0008150",]
  
  # Remove generic "cellular_component"  category
  df1 <- df1[df1$GOslim != "GO:0005575",]
  df2 <- df2[df2$GOslim != "GO:0005575",]
  
  
  # Remove generic "molecular_function"  category
  df1 <- df1[df1$GOslim != "GO:0003674",]
  df2 <- df2[df2$GOslim != "GO:0003674",]
  
  # Select columns
  df1 <- df1 %>% select(Term, Percent)
  df2 <- df2 %>% select(Term, Percent)
  
  # Create treatment column and assign term to all rows
  df1$treatment <- treatment_01
  df2$treatment <- treatment_02
  
  # Concatenate dataframes
  df3 <- rbind(df1, df2)
  
  # Filename for plot
  pyramid <- paste(comparison, "GOslims", "BP", "png", sep = ".")
  pyramid_path <- paste(comparison, pyramid, sep = "/")
  pyramid_dest <- file.path("figures", pyramid_path)
  
  # "Open" PNG file for saving subsequent plot
  png(pyramid_dest, width = 600, height = 1200, units = "px", pointsize = 12)
  
  # Create "pyramid" plot
  pyramid_plot <- ggplot(df3, aes(x = Term, fill = treatment,
                  y = ifelse(test = treatment == treatment_01,
                             yes = -Percent,
                             no = Percent))) +
    geom_bar(stat = "identity") +
    scale_y_continuous(labels = abs, limits = max(df3$Percent) * c(-1,1)) +
    labs(title = "Percentages of GO terms assigned to BP GOslims", x = "GOslim", y = "Percent GO terms in GOslim") +
    scale_x_discrete(expand = c(-1,0)) +
    coord_flip()
  
  # "Prints" the plot so it can be saved to a file.
  print(pyramid_plot)
  
  # Close PNG file
  dev.off()
  # 
  
}

